# Generated by Django 3.2.3 on 2021-07-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_empuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empuser',
            name='utype',
        ),
        migrations.AddField(
            model_name='empuser',
            name='isemp',
            field=models.NullBooleanField(),
        ),
    ]
