# Generated by Django 3.2.3 on 2021-07-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210708_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empuser',
            name='isemp',
            field=models.BooleanField(null=True),
        ),
    ]
