# Generated by Django 3.2.3 on 2021-07-08 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novacustomermodule', '0009_alter_techsupport_sdate'),
        ('users', '0004_alter_empuser_isemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='empuser',
            name='techsup',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='novacustomermodule.techsupport'),
        ),
    ]
