# Generated by Django 3.2.3 on 2021-07-08 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_empuser_techsup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empuser',
            name='techsup',
        ),
    ]
