# Generated by Django 3.2.3 on 2021-07-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_empuser_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empuser',
            name='client',
        ),
    ]
