# Generated by Django 3.2.3 on 2021-07-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_empuser_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='empuser',
            name='status',
            field=models.CharField(default='Offline', max_length=100),
        ),
    ]
