# Generated by Django 3.2.3 on 2021-07-22 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_empuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='empuser',
            name='empnamecpy',
            field=models.CharField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=200),
        ),
    ]
