# Generated by Django 3.2.3 on 2021-07-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_empuser_empnamecpy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empuser',
            name='empnamecpy',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
