# Generated by Django 3.2.3 on 2021-07-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_empuser_empnamecpy'),
    ]

    operations = [
        migrations.AddField(
            model_name='empuser',
            name='updateflag',
            field=models.BooleanField(default=False),
        ),
    ]
