# Generated by Django 3.2.3 on 2021-07-22 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_empuser_updateflag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empuser',
            name='updateflag',
        ),
    ]
