# Generated by Django 3.2.3 on 2021-07-22 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_empuser_nameflag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empuser',
            name='nameflag',
        ),
    ]
