# Generated by Django 3.2.3 on 2021-08-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_phoneofclnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneofclnt',
            name='phoneNumber',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
