# Generated by Django 3.2.3 on 2021-08-30 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_phoneofclnt_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phoneofclnt',
            old_name='phoneNumber',
            new_name='pno',
        ),
    ]
