# Generated by Django 3.2.3 on 2021-08-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_rename_phonenumber_phoneofclnt_pno'),
    ]

    operations = [
        migrations.AddField(
            model_name='empuser',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
