# Generated by Django 3.2.3 on 2021-05-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tallynetid', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('tallyserialno', models.CharField(max_length=25)),
                ('phoneno', models.CharField(max_length=13)),
                ('companyname', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('pan', models.CharField(max_length=15)),
                ('gsttin', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('zip', models.CharField(max_length=25)),
            ],
        ),
    ]
