# Generated by Django 3.2.3 on 2021-07-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novacustomermodule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daybook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vouchertype', models.CharField(max_length=100)),
                ('vouchernumber', models.CharField(max_length=100)),
                ('partyledger', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=15)),
            ],
        ),
    ]
