# Generated by Django 3.2.3 on 2021-07-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novacustomermodule', '0002_daybook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daybook',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
