# Generated by Django 3.2.3 on 2021-07-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novacustomermodule', '0003_alter_daybook_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daybook',
            name='amount',
            field=models.FloatField(max_length=15),
        ),
    ]
