# Generated by Django 3.2.3 on 2021-07-06 07:10

from django.db import migrations, models




class Migration(migrations.Migration):

    dependencies = [
        ('novacustomermodule', '0005_alter_daybook_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Techsupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdate', models.DateField()),
                ('scmp', models.CharField(max_length=100)),
                ('suser', models.CharField(max_length=100)),
                ('sphno', models.CharField(max_length=10)),
                ('sprdt', models.CharField(max_length=100)),
                ('sdetail', models.CharField(max_length=500)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='ss')),
            ],
        ),
    ]
