# Generated by Django 3.2.3 on 2021-07-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novacustomermodule', '0008_alter_techsupport_sdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techsupport',
            name='sdate',
            field=models.CharField(max_length=50),
        ),
    ]
