# Generated by Django 3.2.3 on 2021-07-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novacustomermodule', '0010_alter_techsupport_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techsupport',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='ss'),
        ),
    ]
