# Generated by Django 3.2.3 on 2021-07-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novacustomermodule', '0011_alter_techsupport_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='techsupport',
            name='allot',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='techsupport',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
