# Generated by Django 3.2.3 on 2021-07-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novacustomermodule', '0013_alter_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techsupport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
