# Generated by Django 3.2.3 on 2021-07-12 09:38

from django.db import migrations, models
import novacustomermodule.models


class Migration(migrations.Migration):

    dependencies = [
        ('novacustomermodule', '0015_alter_daybook_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daybook',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='techsupport',
            name='id',
            field=models.BigAutoField(auto_created=True, default=novacustomermodule.models.increment_booking_number, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
