# Generated by Django 3.2.3 on 2021-07-12 10:20

from django.db import migrations, models
import novacustomermodule.models


class Migration(migrations.Migration):

    dependencies = [
        ('novacustomermodule', '0017_alter_techsupport_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techsupport',
            name='id',
            field=models.CharField(auto_created=True, default=novacustomermodule.models.increment_booking_number, max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
