# Generated by Django 3.2.3 on 2021-07-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novacustomermodule', '0018_alter_techsupport_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='techsupport',
            name='st',
            field=models.TimeField(auto_now=True),
        ),
    ]
