# Generated by Django 3.2.3 on 2021-07-23 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novacustomermodule', '0036_alter_techsupport_st'),
    ]

    operations = [
        migrations.AddField(
            model_name='techsupport',
            name='endtime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='techsupport',
            name='starttime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='techsupport',
            name='totaltime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='techsupport',
            name='st',
            field=models.TimeField(default=datetime.datetime(2021, 7, 23, 11, 30, 32, 894638)),
        ),
    ]
