# Generated by Django 3.2.3 on 2021-07-23 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novacustomermodule', '0038_auto_20210723_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techsupport',
            name='st',
            field=models.TimeField(default=datetime.datetime(2021, 7, 23, 17, 26, 46, 449943)),
        ),
    ]
