# Generated by Django 3.2.3 on 2021-07-23 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novacustomermodule', '0040_alter_techsupport_st'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techsupport',
            name='endtime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='techsupport',
            name='st',
            field=models.TimeField(default=datetime.datetime(2021, 7, 23, 18, 5, 45, 454309)),
        ),
        migrations.AlterField(
            model_name='techsupport',
            name='starttime',
            field=models.TimeField(null=True),
        ),
    ]
