# Generated by Django 3.2.3 on 2021-07-24 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novacustomermodule', '0041_auto_20210723_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techsupport',
            name='st',
            field=models.TimeField(default=datetime.datetime(2021, 7, 24, 11, 10, 44, 767032)),
        ),
    ]
