# Generated by Django 3.2.3 on 2021-07-24 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novacustomermodule', '0043_auto_20210724_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techsupport',
            name='endtime',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='techsupport',
            name='st',
            field=models.TimeField(default=datetime.datetime(2021, 7, 24, 12, 19, 27, 820598)),
        ),
        migrations.AlterField(
            model_name='techsupport',
            name='starttime',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='techsupport',
            name='totaltime',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
