# Generated by Django 3.2.3 on 2021-07-28 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novacustomermodule', '0044_auto_20210724_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techsupport',
            name='st',
            field=models.TimeField(default=datetime.datetime(2021, 7, 28, 11, 8, 21, 987902)),
        ),
    ]
