# Generated by Django 3.2.3 on 2021-07-28 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novacustomermodule', '0046_alter_techsupport_st'),
    ]

    operations = [
        migrations.AddField(
            model_name='techsupport',
            name='taskclear',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='techsupport',
            name='st',
            field=models.TimeField(default=datetime.datetime(2021, 7, 28, 12, 4, 26, 25289)),
        ),
    ]
