# Generated by Django 3.2.3 on 2021-07-28 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novacustomermodule', '0047_auto_20210728_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techsupport',
            name='st',
            field=models.TimeField(default=datetime.datetime(2021, 7, 28, 14, 32, 52, 414783)),
        ),
    ]
