# Generated by Django 3.2.3 on 2021-07-31 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novacustomermodule', '0049_auto_20210731_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techsupport',
            name='st',
            field=models.TimeField(default=datetime.datetime(2021, 7, 31, 11, 26, 26, 248387)),
        ),
    ]
