# Generated by Django 3.2.3 on 2021-08-04 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novacustomermodule', '0053_alter_techsupport_st'),
    ]

    operations = [
        migrations.AddField(
            model_name='techsupport',
            name='suprtdate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='techsupport',
            name='st',
            field=models.TimeField(default=datetime.datetime(2021, 8, 4, 11, 17, 7, 132566)),
        ),
    ]
