# Generated by Django 3.2.3 on 2021-08-05 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novacustomermodule', '0054_auto_20210804_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techsupport',
            name='st',
            field=models.TimeField(default=datetime.datetime(2021, 8, 5, 16, 12, 1, 754810)),
        ),
    ]
