# Generated by Django 3.2.3 on 2021-08-28 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novacustomermodule', '0060_alter_techsupport_st'),
    ]

    operations = [
        migrations.AddField(
            model_name='techsupport',
            name='current_endtime',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='techsupport',
            name='intial_starttime',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='techsupport',
            name='st',
            field=models.TimeField(default=datetime.datetime(2021, 8, 28, 12, 41, 21, 756568)),
        ),
    ]
