# Generated by Django 3.2.3 on 2021-08-28 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novacustomermodule', '0061_auto_20210828_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='techsupport',
            name='currentendflg',
            field=models.CharField(default='False', max_length=100),
        ),
        migrations.AddField(
            model_name='techsupport',
            name='intialflg',
            field=models.CharField(default='False', max_length=100),
        ),
        migrations.AlterField(
            model_name='techsupport',
            name='st',
            field=models.TimeField(default=datetime.datetime(2021, 8, 28, 12, 45, 53, 312929)),
        ),
    ]
