# Generated by Django 3.2.3 on 2021-08-28 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novacustomermodule', '0062_auto_20210828_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techsupport',
            name='st',
            field=models.TimeField(default=datetime.datetime(2021, 8, 28, 13, 1, 23, 720908)),
        ),
    ]
