# Generated by Django 3.2.3 on 2021-08-28 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novacustomermodule', '0063_alter_techsupport_st'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techsupport',
            name='st',
            field=models.TimeField(default=datetime.datetime(2021, 8, 28, 13, 3, 11, 654615)),
        ),
    ]
