# Generated by Django 3.2.3 on 2021-08-30 08:48

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('novacustomermodule', '0066_alter_techsupport_st'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phoneno',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='techsupport',
            name='st',
            field=models.TimeField(default=datetime.datetime(2021, 8, 30, 14, 20, 42, 279284)),
        ),
    ]
