# Generated by Django 3.2.3 on 2021-08-30 08:51

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('novacustomermodule', '0067_auto_20210830_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techsupport',
            name='sphno',
        ),
        migrations.AddField(
            model_name='techsupport',
            name='phoneno',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='phoneno',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='techsupport',
            name='st',
            field=models.TimeField(default=datetime.datetime(2021, 8, 30, 14, 23, 4, 29660)),
        ),
    ]
