# Generated by Django 3.2.3 on 2021-08-30 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novacustomermodule', '0068_auto_20210830_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techsupport',
            name='phoneno',
        ),
        migrations.AddField(
            model_name='techsupport',
            name='sphno',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='techsupport',
            name='st',
            field=models.TimeField(default=datetime.datetime(2021, 8, 30, 14, 28, 56, 127933)),
        ),
    ]
