# Generated by Django 3.2.3 on 2021-08-30 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novacustomermodule', '0069_auto_20210830_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techsupport',
            name='st',
            field=models.TimeField(default=datetime.datetime(2021, 8, 30, 14, 31, 10, 10471)),
        ),
    ]
