# Generated by Django 3.2 on 2021-04-24 12:01

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('properitorpic', models.ImageField(blank=True, null=True, upload_to='adsimages')),
                ('directorname', models.CharField(max_length=100, null=True)),
                ('position', models.CharField(max_length=100)),
                ('properitorabt', models.CharField(max_length=200)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adsimg', models.ImageField(blank=True, null=True, upload_to='adsimages')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('catimg', models.ImageField(blank=True, null=True, upload_to='catimg')),
            ],
        ),
        migrations.CreateModel(
            name='Potsmfg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potname', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('materialtype', models.CharField(max_length=100)),
                ('sizein', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
