# Generated by Django 3.2 on 2021-05-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teracota', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='catimg',
        ),
        migrations.AddField(
            model_name='categories',
            name='imgfrcat',
            field=models.ImageField(blank=True, null=True, upload_to='categorypics'),
        ),
    ]
