# Generated by Django 3.2 on 2021-05-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teracota', '0002_auto_20210510_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedpic', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('title', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=500)),
            ],
        ),
    ]
