# Generated by Django 3.2 on 2021-05-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teracota', '0004_feed_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='feedpic',
            new_name='picforblg',
        ),
    ]
