# Generated by Django 3.2 on 2021-05-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teracota', '0006_auto_20210511_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sliderabt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibtmg', models.ImageField(blank=True, null=True, upload_to='cskabt')),
            ],
        ),
    ]
