# Generated by Django 3.2 on 2021-05-12 14:00

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('teracota', '0007_sliderabt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eyusr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('phno', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('mail', models.EmailField(max_length=100)),
                ('details', models.EmailField(max_length=500)),
            ],
        ),
    ]
