# Generated by Django 3.2 on 2021-08-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teracota', '0008_eyusr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('size', models.CharField(max_length=10, null=True)),
                ('discription', models.CharField(max_length=200, null=True)),
                ('purpose', models.CharField(max_length=25, null=True)),
                ('material', models.CharField(max_length=10, null=True)),
                ('category', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Special2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('size', models.CharField(max_length=10, null=True)),
                ('discription', models.CharField(max_length=200, null=True)),
                ('purpose', models.CharField(max_length=25, null=True)),
                ('material', models.CharField(max_length=10, null=True)),
                ('category', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Special3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('size', models.CharField(max_length=10, null=True)),
                ('discription', models.CharField(max_length=200, null=True)),
                ('purpose', models.CharField(max_length=25, null=True)),
                ('material', models.CharField(max_length=10, null=True)),
                ('category', models.CharField(max_length=25, null=True)),
            ],
        ),
    ]
