# Generated by Django 3.2 on 2021-08-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teracota', '0009_special1_special2_special3'),
    ]

    operations = [
        migrations.AddField(
            model_name='special1',
            name='season',
            field=models.ImageField(blank=True, null=True, upload_to='special'),
        ),
        migrations.AddField(
            model_name='special2',
            name='season',
            field=models.ImageField(blank=True, null=True, upload_to='special'),
        ),
        migrations.AddField(
            model_name='special3',
            name='season',
            field=models.ImageField(blank=True, null=True, upload_to='special'),
        ),
    ]
