# Generated by Django 3.2 on 2021-08-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teracota', '0010_auto_20210807_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='Event',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='discription',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='title',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
