# Generated by Django 3.2 on 2021-08-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teracota', '0011_auto_20210807_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='Eflg',
            field=models.CharField(default='False', max_length=6),
        ),
    ]
