# Generated by Django 3.2 on 2021-08-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teracota', '0012_ads_eflg'),
    ]

    operations = [
        migrations.AddField(
            model_name='potsmfg',
            name='discription',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='potsmfg',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='potsmfg',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='potsmfg',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='potsmfg',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='potsmfg',
            name='price',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='potsmfg',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='potsmfg',
            name='size',
            field=models.CharField(max_length=100),
        ),
    ]
