# Generated by Django 3.2 on 2021-08-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teracota', '0013_auto_20210809_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='special1',
            name='season1',
            field=models.ImageField(blank=True, null=True, upload_to='special'),
        ),
        migrations.AddField(
            model_name='special1',
            name='season2',
            field=models.ImageField(blank=True, null=True, upload_to='special'),
        ),
        migrations.AddField(
            model_name='special1',
            name='season3',
            field=models.ImageField(blank=True, null=True, upload_to='special'),
        ),
        migrations.AddField(
            model_name='special1',
            name='season4',
            field=models.ImageField(blank=True, null=True, upload_to='special'),
        ),
    ]
