# Generated by Django 3.2 on 2021-08-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teracota', '0014_auto_20210809_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potsmfg',
            name='size',
        ),
        migrations.RemoveField(
            model_name='potsmfg',
            name='sizein',
        ),
        migrations.AddField(
            model_name='potsmfg',
            name='size1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='potsmfg',
            name='size2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='potsmfg',
            name='size3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='potsmfg',
            name='size4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='potsmfg',
            name='size5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='potsmfg',
            name='size6',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='potsmfg',
            name='size7',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='potsmfg',
            name='size8',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='potsmfg',
            name='size9',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='potsmfg',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
