# Generated by Django 3.2 on 2021-08-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teracota', '0015_auto_20210810_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='potsmfg',
            name='Amount1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='potsmfg',
            name='Amount2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='potsmfg',
            name='Amount3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='potsmfg',
            name='Amount4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='potsmfg',
            name='Amount5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='potsmfg',
            name='Amount6',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='potsmfg',
            name='Amount7',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='potsmfg',
            name='Amount8',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='potsmfg',
            name='Amount9',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
