# Generated by Django 3.2 on 2021-08-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teracota', '0016_auto_20210810_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='potsmfg',
            name='Amount1',
        ),
        migrations.RemoveField(
            model_name='potsmfg',
            name='Amount2',
        ),
        migrations.RemoveField(
            model_name='potsmfg',
            name='Amount3',
        ),
        migrations.RemoveField(
            model_name='potsmfg',
            name='Amount4',
        ),
        migrations.RemoveField(
            model_name='potsmfg',
            name='Amount5',
        ),
        migrations.RemoveField(
            model_name='potsmfg',
            name='Amount6',
        ),
        migrations.RemoveField(
            model_name='potsmfg',
            name='Amount7',
        ),
        migrations.RemoveField(
            model_name='potsmfg',
            name='Amount8',
        ),
        migrations.RemoveField(
            model_name='potsmfg',
            name='Amount9',
        ),
        migrations.RemoveField(
            model_name='potsmfg',
            name='price',
        ),
        migrations.RemoveField(
            model_name='potsmfg',
            name='size1',
        ),
        migrations.RemoveField(
            model_name='potsmfg',
            name='size2',
        ),
        migrations.RemoveField(
            model_name='potsmfg',
            name='size3',
        ),
        migrations.RemoveField(
            model_name='potsmfg',
            name='size4',
        ),
        migrations.RemoveField(
            model_name='potsmfg',
            name='size5',
        ),
        migrations.RemoveField(
            model_name='potsmfg',
            name='size6',
        ),
        migrations.RemoveField(
            model_name='potsmfg',
            name='size7',
        ),
        migrations.RemoveField(
            model_name='potsmfg',
            name='size8',
        ),
        migrations.RemoveField(
            model_name='potsmfg',
            name='size9',
        ),
    ]
