# Generated by Django 3.2 on 2021-08-11 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teracota', '0017_auto_20210811_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='pid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='teracota.potsmfg'),
        ),
    ]
