# Generated by Django 3.2 on 2021-08-11 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teracota', '0018_pricelist_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teracota.potsmfg'),
        ),
    ]
