# Generated by Django 3.2 on 2021-08-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teracota', '0019_alter_pricelist_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('size', models.CharField(max_length=100, null=True)),
                ('quantity', models.CharField(max_length=100, null=True)),
                ('baseprice', models.CharField(max_length=25, null=True)),
                ('kartimg', models.CharField(max_length=50, null=True)),
                ('totalprice', models.CharField(max_length=25, null=True)),
            ],
        ),
    ]
