# Generated by Django 3.2 on 2021-08-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teracota', '0020_myorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='kartimg',
            field=models.ImageField(blank=True, null=True, upload_to='Kart'),
        ),
    ]
