# Generated by Django 3.2 on 2021-08-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teracota', '0023_special1_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='special3',
            name='price',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
