# Generated by Django 3.2 on 2021-08-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teracota', '0024_special3_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='phone',
        ),
        migrations.AddField(
            model_name='myorder',
            name='Email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myorder',
            name='address1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myorder',
            name='address2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myorder',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myorder',
            name='phno',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='myorder',
            name='pincode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='myorder',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
