# Generated by Django 3.2 on 2021-08-15 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teracota', '0025_auto_20210815_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eyusr',
            name='phno',
        ),
    ]
