# Generated by Django 3.2 on 2021-08-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teracota', '0027_auto_20210815_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='mailflag',
            field=models.CharField(default='', max_length=10),
        ),
    ]
