# Generated by Django 3.2 on 2021-08-16 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teracota', '0028_myorder_mailflag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorder',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='myorder',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='myorder',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='myorder',
            name='city',
        ),
        migrations.RemoveField(
            model_name='myorder',
            name='phno',
        ),
        migrations.RemoveField(
            model_name='myorder',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='myorder',
            name='state',
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phno', models.CharField(max_length=11, null=True)),
                ('Email', models.CharField(max_length=100, null=True)),
                ('address1', models.CharField(max_length=100, null=True)),
                ('address2', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('pincode', models.CharField(max_length=10, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('fcm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teracota.myorder')),
            ],
        ),
    ]
