# Generated by Django 3.2 on 2021-08-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teracota', '0029_auto_20210816_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
