# Generated by Django 3.2 on 2021-08-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teracota', '0031_auto_20210816_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='mailflag',
            field=models.CharField(default='false', max_length=10),
        ),
    ]
