# Generated by Django 3.2.3 on 2021-07-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mysupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empsdate', models.CharField(max_length=50)),
                ('empsscmp', models.CharField(max_length=100)),
                ('empssuser', models.CharField(max_length=100)),
                ('empssphno', models.CharField(max_length=10)),
                ('empssprdt', models.CharField(max_length=100)),
                ('empssdetail', models.CharField(max_length=500)),
                ('empsscreenshot', models.ImageField(blank=True, null=True, upload_to='support')),
            ],
        ),
    ]
