# Generated by Django 3.2.3 on 2021-07-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novaadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysupport',
            name='empname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
