# Generated by Django 3.2.3 on 2021-07-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novaadmin', '0003_alter_mysupport_empsscreenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysupport',
            name='empsscreenshot',
            field=models.ImageField(blank=True, null=True, upload_to='support'),
        ),
    ]
