# Generated by Django 3.2.3 on 2021-07-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novaadmin', '0004_alter_mysupport_empsscreenshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysupport',
            old_name='empname',
            new_name='empallot',
        ),
        migrations.RemoveField(
            model_name='mysupport',
            name='empsscmp',
        ),
        migrations.RemoveField(
            model_name='mysupport',
            name='empsscreenshot',
        ),
        migrations.RemoveField(
            model_name='mysupport',
            name='empssphno',
        ),
        migrations.RemoveField(
            model_name='mysupport',
            name='empssprdt',
        ),
        migrations.RemoveField(
            model_name='mysupport',
            name='empssuser',
        ),
        migrations.AddField(
            model_name='mysupport',
            name='empcmp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mysupport',
            name='empsid',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mysupport',
            name='emptotaltime',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mysupport',
            name='sstatus',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='mysupport',
            name='stype',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mysupport',
            name='empsdate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mysupport',
            name='empssdetail',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
