# Generated by Django 3.2.3 on 2021-08-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novaadmin', '0006_mysupport_empsprfct'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysupport',
            name='mailflag',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
