# Generated by Django 3.2.3 on 2021-08-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novaadmin', '0007_mysupport_mailflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysupport',
            name='mailflag',
            field=models.CharField(default='False', max_length=10, null=True),
        ),
    ]
