# Generated by Django 3.2.3 on 2021-08-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novaadmin', '0009_alter_mysupport_mailflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysupport',
            name='timesheetflag',
            field=models.CharField(default='False', max_length=10),
        ),
    ]
