# Generated by Django 3.2.3 on 2021-08-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novaadmin', '0010_mysupport_timesheetflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysupport',
            name='empreslvd',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
