# Generated by Django 3.2.3 on 2021-08-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novaadmin', '0011_mysupport_empreslvd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysupport',
            name='empreslvd',
        ),
    ]
