# Generated by Django 3.2.3 on 2021-08-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novaadmin', '0012_remove_mysupport_empreslvd'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysupport',
            name='endtimecurrent',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mysupport',
            name='intialtime',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
